sudo: required

services:
  - docker

script:
  - docker-compose up -d
  - docker-compose ps
  - PG_IP=$(docker inspect --format='{{.NetworkSettings.IPAddress}}' travisciprodregular_postgres_1)
  - echo $PG_IP
  - sleep 600

install: true

