sudo: required

services:
  - docker

before_install:
  - docker-compose up -d
  - docker-compose ps
  - PG_IP=$(docker inspect --format='{{.NetworkSettings.IPAddress}}' travisciprodregular_postgres_1)
  - echo $PG_IP

install: true

script:
  - PGPASSWORD=postgres psql -h $PG_IP -p 5432 -U postgres --list
  - docker inspect travisciprodregular_postgres_1
